Sc 6651
pin-people/event_people_node pull request #3
Opened 2022-10-28 18:58 UTC by Badaueba

## Problem
Dependency of dotenv library
No coverage for event-people-node

## Solution
Removing dotenv library
Adding unit tests for rabbit broker

## Checklist before code review
- [ ] Circle CI checks passed?
- [ ] Your branch is updated(rebased) with master?
- [ ] Did you write tests for your task, including regression tests?

## Reviewer Checklist
- [ ] I checked if the task has the tests
- [ ] I checked if the task has no security breach
- [ ] I checked if the task doesn't have unoptimized queries

## Checklist after merge
- [ ] If it's a _Sentry_ issue, mark it as resolved.
- [ ] Confirm deploy pass
- [ ] Notify product-team

## Deploy Notes
_Notes regarding deployment of the contained body of work. These should note any
new dependencies, new scripts, etc._

**New environment variables**:
- `env var` : env var details

**New scripts**:
- `script` : script details

**New dependencies**:
- `dependency` : dependency details

**New dev dependencies**:
- `dependency` : dependency details

2022-10-28 19:22 UTC, m4theuspereira-maker commented on test/mock/constants.ts
> +export const RABBIT_URL = 'amqp://admin:admin@127.0.0.1:5672';
why not import vars from example of they are equals

2022-10-28 19:22 UTC, m4theuspereira-maker commented on test/mock/constants.ts
> +export const RABBIT_EVENT_PEOPLE_VHOST = 'event_people';
In this case there're two options, exclude this files and import directly from prod costs, or create other consts just used for mock, like:

```
RABBIT_URL='any_url:any@1.2.4.5:6789
```

2022-11-03 19:34 UTC, willianbvsanches13 requested changes

2022-11-03 19:34 UTC, willianbvsanches13 commented on lib/broker/rabbit/rabbit-broker.ts
> +			this.connection = await connect(Config.FUll_URL);
you need to captalize the "l" too

2022-11-03 20:23 UTC, m4theuspereira-maker approved these changes

2022-11-03 20:34 UTC, willianbvsanches13 approved these changes

2022-11-03 20:49 UTC, merged